using System.Text.Json.Serialization;
using Maib.Checkout.Api.Connector.Models.Enums;

namespace Maib.Checkout.Api.Connector.Models.Requests;

public record CreateCheckoutRequest : BaseRequest
{
    protected override string Action => "/checkouts";

    /// <summary>
    /// Transaction amount. Format: X.XX (≥1)
    /// 
    /// E.g: 10.25 (currency=USD) means $10 and 25 cents.
    /// </summary>
    [JsonPropertyName("amount")]
    public decimal Amount { get; set; }

    /// <summary>
    /// Transaction currency (MDL/EUR/USD)
    /// </summary>
    [JsonPropertyName("currency")]
    public Currency Currency { get; set; }

    /// <summary>
    /// Language maib ecomm checkout page.
    /// 
    /// Allowed values: ro/en/ru
    /// 
    /// If this parameter is not passed, the page will be displayed in English.
    /// </summary>
    [JsonPropertyName("language")]
    public Language? Language { get; set; }

    /// <summary>
    /// Order generated by Merchant website/app
    /// </summary>
    [JsonPropertyName("orderInfo")]
    public OrderDto? Order { get; set; }
    
    /// <summary>
    /// Information about customer
    /// </summary>
    [JsonPropertyName("payerInfo")]
    public PayerDto? Payer { get; set; }

    /// <summary>
    /// The link where the Merchant will receive the final response with the transaction status and data.
    /// 
    /// If this parameter is not passed, its value will be taken from merchant payment profile
    /// </summary>
    [JsonPropertyName("callbackUrl")]
    public string? CallbackUrl { get; set; }

    /// <summary>
    /// The link where the Customer will be redirected if the transaction was successful.
    /// 
    /// If this parameter is not passed, its value will be taken from merchant payment profile
    /// </summary>
    [JsonPropertyName("successUrl")]
    public string? SuccessUrl { get; set; }

    /// <summary>
    /// The link where the Customer will be redirected if the transaction was failed.
    /// 
    /// If this parameter is not passed, its value will be taken from merchant payment profile
    /// </summary>
    [JsonPropertyName("failUrl")]
    public string? FailUrl { get; set; }
}